name = "Fogger Pack"
author = "CookieJAR499 & Co"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a11016ed1d0559bad458f6949e0b48b6d536bbd922d2378ed7ffcbfd54941ec"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
