name = "Fogger Pack"
author = "CookieJAR499 & Co"
version = "2.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c67bfd812375b183c42de686b4568da935238b1abf316aceeb0ae320ca606b1"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
