name = "Fogger Pack"
author = "CookieJAR499 & Co"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8427f272eb92df86780662dc99f61111303b20f3bd244f40f44ec12abee9a15a"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
