name = "Fogger Pack"
author = "CookieJAR499 & Co"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "131eacb06a53117b408bf530894b59a3d23707c7702576c422ce7222709be4ff"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"
