name = "Fogger Pack"
author = "CookieJAR499 & Co"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f86e7dc5d11416ddf841e387d83197b6284fe5c14591688a1d9cf61d53697968"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
