name = "Fogger Pack"
author = "CookieJAR499 & Co"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb0ff60b672b5cb8d2e5ca0d371d9d9bb1695af485454a6fdb06cebab6badb8f"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
