name = "Fogger Pack"
author = "CookieJAR499 & Co"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddb00b94b4626d046e36de48d8b89eb642bf154d16278629fb9d754f89627984"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
