name = "Fogger Pack"
author = "CookieJAR499 & Co"
version = "2.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c475f19e74aa1af6ea575d5da0e9f286ee14a0fe5a765e1c7973f6c52e465c3d"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
