name = "Fogger Pack"
author = "CookieJAR499 & Co"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98da42ef4092c97d5b26e2540e10e52e22934c87cf77ad1b3ca4ff49cc131acd"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
