name = "Fogger Pack"
author = "CookieJAR499 & Co"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86d15a3d3e81ae1cd51c72e9f9716ce045bc473ee38a3e1409a1b511b2b4ab27"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
