name = "Fogger Pack"
author = "CookieJAR499 & Co"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c8844451d816549e8357e62ada07763a5c15f309b04a1507b7c64917375fdbe"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"
