name = "Fogger Pack"
author = "CookieJAR499 & Co"
version = "2.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab965f1b3c33276aecb923bd378df79e99dda0c010d26ee1c5a390f77451535e"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
