name = "Fogger Pack"
author = "CookieJAR499 & Co"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8e2d7e29390638870062878baf00a095b688171d28817299e8e8e7dff10cc85"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
