name = "Fogger Pack"
author = "CookieJAR499 & Co"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cdfebcba1ecac60d678746f817483cd0e2cc9b90896316ff197cd094fd2efa2"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"
