name = "Fogger Pack"
author = "CookieJAR499 & Co"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32c4b1112572f3b97edee6e9a1cb613bee11597b483c0f32b3556a2cdf6128c5"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
