name = "Fogger Pack"
author = "CookieJAR499 & Co"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dac2f049a6fda0fe8a05a61c223db95016fa34b7c9b4c295ed993befa65c83c6"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"
