name = "Fogger Pack"
author = "CookieJAR499 & Co"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74ab6d27c4b69b28e226550671ad75c328ef99a1581bffb60895802df8d6e11f"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"
