[restrictions]
talkRange = 100
shoutTalkRange = 100
shoutFoodCost = 2147483647
opAsPlayer = false
[miscellaneous]
prefix = ""
usePrefix = false
rangeNotifier = true
[color_codes]
bracketColor = "§6"
angleBraceColor = "§7"
posColor = "§e"
nameColor = "§f"
bodyColor = "§f"
defaultColor = "§f"
