[restrictions]
talkRange = 30
shoutTalkRange = 70
shoutFoodCost = 5
opAsPlayer = false
[miscellaneous]
prefix = ""
usePrefix = false
rangeNotifier = true
[color_codes]
bracketColor = "§6"
angleBraceColor = "§7"
posColor = "§e"
nameColor = "§f"
bodyColor = "§f"
defaultColor = "§f"
